scope: prd-cuber1-patroni-cls2
name: pg_node_1
namespace: prd/cuber1/patroni/cls2

log:
  level: INFO
  traceback_level: ERROR
  format: "%(asctime)s %(levelname)s: %(message)s"
  dateformat: ""
  max_queue_size: 1000
  dir: /var/log/patroni
  file_num: 4
  file_size: 25000000
  loggers:
    patroni.postmaster: WARNING
    urllib3: WARNING

restapi:
  listen: 10.77.120.7:8008
  connect_address: 10.77.120.7:8008

consul:
  host: 127.0.0.1:8500
  token: 126546dc-253e-ec27-37cb-9159e35c0861
  register_service: true
  checks: []

bootstrap:
  dcs:
    ttl: 100
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: false
    synchronous_mode_strict: false
    synchronous_node_count: 1
    master_start_timeout: 300
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: hot_standby
        hot_standby: on
        wal_keep_size: 2048MB
        max_wal_senders: 10
        max_connections: 100
        superuser_reserved_connections: 5
        port: 5432
        listen_addresses: '*'
        data_directory: '/opt/databases/13/main'
        password_encryption: 'scram-sha-256'
        max_locks_per_transaction: 64
        max_prepared_transactions: 0
        huge_pages: try
        shared_buffers: 512MB
        work_mem: 5242kB
        maintenance_work_mem: 128MB
        effective_cache_size: 1536MB
        wal_buffers: 16MB
        checkpoint_timeout: 10min
        checkpoint_completion_target: 0.9
        min_wal_size: 2GB
        max_wal_size: 8GB
        default_statistics_target: 100
        seq_page_cost: 1
        random_page_cost: 4
        effective_io_concurrency: 2
        synchronous_commit: on
        autovacuum: on
        autovacuum_max_workers: 3
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_vacuum_cost_limit: -1
        autovacuum_vacuum_cost_delay: 20
        autovacuum_vacuum_threshold: 50
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_analyze_threshold: 50
        autovacuum_naptime: 30
        vacuum_cost_limit: 500
        max_files_per_process: 1024
        archive_mode: on
        archive_timeout: 0
        archive_command: '/usr/local/bin/wal-g --config /home/postgres/dbi/config/.walg.json wal-push "%p" >> /var/log/postgresql/archive_command.log 2>&1'
        wal_level: replica
        wal_keep_segments: 100
        max_wal_senders: 5
        max_replication_slots: 5
        hot_standby: on
        wal_log_hints: on
        full_page_writes: on
        wal_sync_method: fdatasync
        fsync: on
        jit: off
        shared_preload_libraries: pg_stat_statements
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        pg_stat_statements.save: on
        track_io_timing: on
        track_activity_query_size: 2048
        log_lock_waits: on
        log_temp_files: 0
        track_activities: on
        track_counts: on
        track_functions: all
        log_checkpoints: on
        logging_collector: on
        log_truncate_on_rotation: on
        log_rotation_age: 360
        log_rotation_size: 0
        log_line_prefix: '%m [%p]: user=%u,db=%d,app=%a,client=%h '
        log_filename: 'postgresql-%Y%m%d_%H%M.log'
        log_directory: '/var/log/postgresql'
        log_min_duration_statement: 1000
        log_checkpoints: on
        log_connections: off
        log_disconnections: off
        log_lock_waits: on
        log_temp_files: 0
        log_autovacuum_min_duration: 0
        log_error_verbosity: default
        max_worker_processes: 2
        max_parallel_workers_per_gather: 1
        max_parallel_workers: 2
        max_parallel_maintenance_workers: 1

  initdb:
  - encoding: UTF8
  - data-checksums
  - locale: en_US.UTF8

  pg_hba:
  - host all all 0.0.0.0/0 md5
  - host replication replicator 127.0.0.1/32 md5

postgresql:
  listen: '0.0.0.0:5432'
  connect_address: 10.77.120.7:5432
  data_dir: /opt/databases/13/main
  bin_dir: /usr/lib/postgresql/13/bin
  config_dir: /etc/postgresql/13/main
  callbacks:
    on_role_change: /home/postgres/dbi/scripts/dns_wrapper.sh
  authentication:
    replication:
      username: replicator
      password: _lm8an5V6qYqE1Wx
    superuser:
      username: patroni
      password: 6ZYmmoZPqT8VnWR2
  parameters:
     unix_socket_directories: '/var/run/postgresql'


watchdog:
  mode: off
  device: /dev/watchdog
  safety_margin: 5


tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false


restapi:
  listen: 10.77.198.26:8801
  connect_address: 10.77.198.26:8801

etcd:
  hosts: 10.77.198.26:2379,10.77.98.26:2379,10.77.36.71:2379
